// Code generated by swag2api v1.0.0. DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/KianIt/swag2api/example/models"
)

type _errorResponse struct {
	Error string `json:"error"`
}

func _unmarshalString[T any](value string) (buf T, err error) {
	return _unmarshalBytes[T]([]byte(value))
}
func _unmarshalBytes[T any](value []byte) (buf T, err error) {
	if err = json.Unmarshal(value, &buf); err != nil {
		return buf, fmt.Errorf("unmarshal: %w", err)
	}
	return buf, nil
}
func _handleBadRequest(w http.ResponseWriter, err error) {
	var (
		code = http.StatusBadRequest
		msg  = http.StatusText(http.StatusBadRequest)
	)
	if err != nil {
		msg = err.Error()
	}
	response := _errorResponse{Error: msg}
	_writeResponse(w, code, response)
}
func _handleResult(w http.ResponseWriter, err error, response any) {
	if err == nil {
		_writeResponse(w, http.StatusOK, response)
		return
	}
	if cu, ok := err.(interface {
		Code() int
		Unwrap() error
	}); ok {
		if e := cu.Unwrap(); e != nil {
			_writeResponse(w, cu.Code(), _errorResponse{Error: e.Error()})
		} else if response == nil {
			_writeResponse(w, cu.Code(), _errorResponse{Error: http.StatusText(cu.Code())})
		} else {
			_writeResponse(w, cu.Code(), response)
		}
		return
	}
	_writeResponse(w, http.StatusInternalServerError, _errorResponse{Error: err.Error()})
}
func _writeResponse(w http.ResponseWriter, code int, response any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(response)
}
func _handler_method1(w http.ResponseWriter, r *http.Request) {
	pathStringPath := r.PathValue("pathString")
	pathString, pathStringUnmarshalErr := _unmarshalString[string](pathStringPath)
	if pathStringUnmarshalErr != nil {
		_handleBadRequest(w, pathStringUnmarshalErr)
		return
	}
	pathIntPath := r.PathValue("pathInt")
	pathInt, pathIntUnmarshalErr := _unmarshalString[int](pathIntPath)
	if pathIntUnmarshalErr != nil {
		_handleBadRequest(w, pathIntUnmarshalErr)
		return
	}
	pathFloat64Path := r.PathValue("pathFloat64")
	pathFloat64, pathFloat64UnmarshalErr := _unmarshalString[float64](pathFloat64Path)
	if pathFloat64UnmarshalErr != nil {
		_handleBadRequest(w, pathFloat64UnmarshalErr)
		return
	}
	pathBoolPath := r.PathValue("pathBool")
	pathBool, pathBoolUnmarshalErr := _unmarshalString[bool](pathBoolPath)
	if pathBoolUnmarshalErr != nil {
		_handleBadRequest(w, pathBoolUnmarshalErr)
		return
	}
	pathBytesPath := r.PathValue("pathBytes")
	pathBytes, pathBytesUnmarshalErr := _unmarshalString[[]byte](pathBytesPath)
	if pathBytesUnmarshalErr != nil {
		_handleBadRequest(w, pathBytesUnmarshalErr)
		return
	}
	result, err := method1(pathString, pathInt, pathFloat64, pathBool, pathBytes)
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, err, _resultValue)
}
func _handler_method10(w http.ResponseWriter, r *http.Request) {
	result, err := method10()
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, err, _resultValue)
}
func _handler_method2(w http.ResponseWriter, r *http.Request) {
	queryStringQuery := r.URL.Query().Get("queryString")
	queryString, queryStringUnmarshalErr := _unmarshalString[string](queryStringQuery)
	if queryStringUnmarshalErr != nil {
		_handleBadRequest(w, queryStringUnmarshalErr)
		return
	}
	queryIntQuery := r.URL.Query().Get("queryInt")
	queryInt, queryIntUnmarshalErr := _unmarshalString[int](queryIntQuery)
	if queryIntUnmarshalErr != nil {
		_handleBadRequest(w, queryIntUnmarshalErr)
		return
	}
	queryFloat64Query := r.URL.Query().Get("queryFloat64")
	queryFloat64, queryFloat64UnmarshalErr := _unmarshalString[float64](queryFloat64Query)
	if queryFloat64UnmarshalErr != nil {
		_handleBadRequest(w, queryFloat64UnmarshalErr)
		return
	}
	queryBoolQuery := r.URL.Query().Get("queryBool")
	queryBool, queryBoolUnmarshalErr := _unmarshalString[bool](queryBoolQuery)
	if queryBoolUnmarshalErr != nil {
		_handleBadRequest(w, queryBoolUnmarshalErr)
		return
	}
	queryBytesQuery := r.URL.Query().Get("queryBytes")
	queryBytes, queryBytesUnmarshalErr := _unmarshalString[[]byte](queryBytesQuery)
	if queryBytesUnmarshalErr != nil {
		_handleBadRequest(w, queryBytesUnmarshalErr)
		return
	}
	_, err := method2(queryString, queryInt, queryFloat64, queryBool, queryBytes)
	type _resultType struct {
	}
	_resultValue := _resultType{}
	_handleResult(w, err, _resultValue)
}
func _handler_method3(w http.ResponseWriter, r *http.Request) {
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	type _bodyType struct {
		BodyString  string  `json:"bodyString"`
		BodyInt     int     `json:"bodyInt"`
		BodyFloat64 float64 `json:"bodyFloat64"`
		BodyBool    bool    `json:"bodyBool"`
		BodyBytes   []byte  `json:"bodyBytes"`
	}
	_bodyValue, _bodyValueUnmarshalErr := _unmarshalBytes[_bodyType](_body)
	if _bodyValueUnmarshalErr != nil {
		_handleBadRequest(w, _bodyValueUnmarshalErr)
		return
	}
	result, _ := method3(_bodyValue.BodyString, _bodyValue.BodyInt, _bodyValue.BodyFloat64, _bodyValue.BodyBool, _bodyValue.BodyBytes)
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, nil, _resultValue)
}
func _handler_method4(w http.ResponseWriter, r *http.Request) {
	pathStringPath := r.PathValue("pathString")
	pathString, pathStringUnmarshalErr := _unmarshalString[string](pathStringPath)
	if pathStringUnmarshalErr != nil {
		_handleBadRequest(w, pathStringUnmarshalErr)
		return
	}
	queryStringQuery := r.URL.Query().Get("queryString")
	queryString, queryStringUnmarshalErr := _unmarshalString[string](queryStringQuery)
	if queryStringUnmarshalErr != nil {
		_handleBadRequest(w, queryStringUnmarshalErr)
		return
	}
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	bodyString, bodyStringUnmarshalErr := _unmarshalBytes[string](_body)
	if bodyStringUnmarshalErr != nil {
		_handleBadRequest(w, bodyStringUnmarshalErr)
		return
	}
	res0, res1 := method4(pathString, queryString, bodyString)
	type _resultType struct {
		Res0 string `json:"res0"`
	}
	_resultValue := _resultType{Res0: res0}
	_handleResult(w, res1, _resultValue)
}
func _handler_method5(w http.ResponseWriter, r *http.Request) {
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	bodyMap, bodyMapUnmarshalErr := _unmarshalBytes[map[string][]map[string]int](_body)
	if bodyMapUnmarshalErr != nil {
		_handleBadRequest(w, bodyMapUnmarshalErr)
		return
	}
	result, Error := method5(bodyMap)
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, Error, _resultValue)
}
func _handler_method6(w http.ResponseWriter, r *http.Request) {
	field1Query := r.URL.Query().Get("field1")
	field1, field1UnmarshalErr := _unmarshalString[string](field1Query)
	if field1UnmarshalErr != nil {
		_handleBadRequest(w, field1UnmarshalErr)
		return
	}
	field2Query := r.URL.Query().Get("field2")
	field2, field2UnmarshalErr := _unmarshalString[int](field2Query)
	if field2UnmarshalErr != nil {
		_handleBadRequest(w, field2UnmarshalErr)
		return
	}
	field3Query := r.URL.Query().Get("field3")
	field3, field3UnmarshalErr := _unmarshalString[float64](field3Query)
	if field3UnmarshalErr != nil {
		_handleBadRequest(w, field3UnmarshalErr)
		return
	}
	field4Query := r.URL.Query().Get("field4")
	field4, field4UnmarshalErr := _unmarshalString[bool](field4Query)
	if field4UnmarshalErr != nil {
		_handleBadRequest(w, field4UnmarshalErr)
		return
	}
	field5Query := r.URL.Query().Get("field5")
	field5, field5UnmarshalErr := _unmarshalString[[]byte](field5Query)
	if field5UnmarshalErr != nil {
		_handleBadRequest(w, field5UnmarshalErr)
		return
	}
	code, err := method6(field1, field2, field3, field4, field5)
	type _resultType struct {
		Code int `json:"code"`
	}
	_resultValue := _resultType{Code: code}
	_handleResult(w, err, _resultValue)
}
func _handler_method7(w http.ResponseWriter, r *http.Request) {
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	type _bodyType struct {
		BodyModel     ThisPackageModel                      `json:"bodyModel"`
		BodyModelList []ThisPackageModel                    `json:"bodyModelList"`
		BodyModelMap  map[string]models.AnotherPackageModel `json:"bodyModelMap"`
	}
	_bodyValue, _bodyValueUnmarshalErr := _unmarshalBytes[_bodyType](_body)
	if _bodyValueUnmarshalErr != nil {
		_handleBadRequest(w, _bodyValueUnmarshalErr)
		return
	}
	code, err := method7(_bodyValue.BodyModel, _bodyValue.BodyModelList, _bodyValue.BodyModelMap)
	type _resultType struct {
		Code int `json:"code"`
	}
	_resultValue := _resultType{Code: code}
	_handleResult(w, err, _resultValue)
}
func _handler_method8(w http.ResponseWriter, r *http.Request) {
	result, err := method8()
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, err, _resultValue)
}
func _handler_method9(w http.ResponseWriter, r *http.Request) {
	result, err := method9()
	type _resultType struct {
		Result string `json:"result"`
	}
	_resultValue := _resultType{Result: result}
	_handleResult(w, err, _resultValue)
}
func init() {
	_mux := http.NewServeMux()
	_mux.HandleFunc("GET /path-to-method1", _handler_method1)
	_mux.HandleFunc("GET /path-to-method10", _handler_method10)
	_mux.HandleFunc("POST /path-to-method2", _handler_method2)
	_mux.HandleFunc("PUT /path-to-method3", _handler_method3)
	_mux.HandleFunc("DELETE /path-to-method4", _handler_method4)
	_mux.HandleFunc("OPTIONS /path-to-method5", _handler_method5)
	_mux.HandleFunc("HEAD /path-to-method6", _handler_method6)
	_mux.HandleFunc("PATCH /path-to-method7", _handler_method7)
	_mux.HandleFunc("GET /path-to-method8", _handler_method8)
	_mux.HandleFunc("GET /path-to-method9", _handler_method9)
	s2aHandler = _mux
}
