// Code generated by swag2api v1.0.0. DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/KianIt/swag2api/example/models"
)

type _baseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg,omitempty"`
}

func _unmarshalString[T any](value string) (buf T, err error) {
	var data []byte
	if strings.Contains(value, ",") {
		data, err = json.Marshal(strings.Split(value, ","))
		if err != nil {
			return buf, fmt.Errorf("list marshal: %w", err)
		}
	} else {
		data = []byte(value)
	}
	return _unmarshalBytes[T](data)
}
func _unmarshalBytes[T any](value []byte) (buf T, err error) {
	if err := json.Unmarshal(value, &buf); err != nil {
		return buf, fmt.Errorf("unmarshal: %w", err)
	}
	return buf, nil
}
func _handleBadRequest(w http.ResponseWriter, err error) {
	var (
		code = http.StatusBadRequest
		msg  = http.StatusText(http.StatusBadRequest)
	)
	if err != nil {
		msg = err.Error()
	}
	response := _baseResponse{Code: code, Msg: msg}
	_writeResponse(w, response.Code, response)
}
func _handleResult(w http.ResponseWriter, err error, response any) {
	if err != nil {
		if cu, ok := err.(interface {
			Code() int
			Unwrap() error
		}); ok {
			if e := cu.Unwrap(); e != nil {
				_writeResponse(w, cu.Code(), _baseResponse{Code: cu.Code(), Msg: e.Error()})
				return
			} else {
				_writeResponse(w, cu.Code(), response)
				return
			}
		} else {
			_writeResponse(w, http.StatusInternalServerError, _baseResponse{Code: http.StatusInternalServerError, Msg: err.Error()})
			return
		}
	}
	_writeResponse(w, http.StatusOK, response)
}
func _writeResponse(w http.ResponseWriter, code int, response any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(response)
}
func _handler_method1(w http.ResponseWriter, r *http.Request) {
	pathStringPath := r.PathValue("pathString")
	pathString, pathStringUnmarshalErr := _unmarshalString[string](pathStringPath)
	if pathStringUnmarshalErr != nil {
		_handleBadRequest(w, pathStringUnmarshalErr)
		return
	}
	pathIntPath := r.PathValue("pathInt")
	pathInt, pathIntUnmarshalErr := _unmarshalString[int](pathIntPath)
	if pathIntUnmarshalErr != nil {
		_handleBadRequest(w, pathIntUnmarshalErr)
		return
	}
	pathFloat64Path := r.PathValue("pathFloat64")
	pathFloat64, pathFloat64UnmarshalErr := _unmarshalString[float64](pathFloat64Path)
	if pathFloat64UnmarshalErr != nil {
		_handleBadRequest(w, pathFloat64UnmarshalErr)
		return
	}
	pathBoolPath := r.PathValue("pathBool")
	pathBool, pathBoolUnmarshalErr := _unmarshalString[bool](pathBoolPath)
	if pathBoolUnmarshalErr != nil {
		_handleBadRequest(w, pathBoolUnmarshalErr)
		return
	}
	pathBytesPath := r.PathValue("pathBytes")
	pathBytes, pathBytesUnmarshalErr := _unmarshalString[[]byte](pathBytesPath)
	if pathBytesUnmarshalErr != nil {
		_handleBadRequest(w, pathBytesUnmarshalErr)
		return
	}
	result, err := method1(pathString, pathInt, pathFloat64, pathBool, pathBytes)
	type resultType struct {
		_baseResponse `json:",inline"`
		Result        string `json:"result"`
		Err           error  `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Result: result, Err: err}
	_handleResult(w, err, resultValue)
}
func _handler_method2(w http.ResponseWriter, r *http.Request) {
	queryStringQuery := r.URL.Query().Get("queryString")
	queryString, queryStringUnmarshalErr := _unmarshalString[string](queryStringQuery)
	if queryStringUnmarshalErr != nil {
		_handleBadRequest(w, queryStringUnmarshalErr)
		return
	}
	queryIntQuery := r.URL.Query().Get("queryInt")
	queryInt, queryIntUnmarshalErr := _unmarshalString[int](queryIntQuery)
	if queryIntUnmarshalErr != nil {
		_handleBadRequest(w, queryIntUnmarshalErr)
		return
	}
	queryFloat64Query := r.URL.Query().Get("queryFloat64")
	queryFloat64, queryFloat64UnmarshalErr := _unmarshalString[float64](queryFloat64Query)
	if queryFloat64UnmarshalErr != nil {
		_handleBadRequest(w, queryFloat64UnmarshalErr)
		return
	}
	queryBoolQuery := r.URL.Query().Get("queryBool")
	queryBool, queryBoolUnmarshalErr := _unmarshalString[bool](queryBoolQuery)
	if queryBoolUnmarshalErr != nil {
		_handleBadRequest(w, queryBoolUnmarshalErr)
		return
	}
	queryBytesQuery := r.URL.Query().Get("queryBytes")
	queryBytes, queryBytesUnmarshalErr := _unmarshalString[[]byte](queryBytesQuery)
	if queryBytesUnmarshalErr != nil {
		_handleBadRequest(w, queryBytesUnmarshalErr)
		return
	}
	_, err := method2(queryString, queryInt, queryFloat64, queryBool, queryBytes)
	type resultType struct {
		_baseResponse `json:",inline"`
		Err           error `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Err: err}
	_handleResult(w, err, resultValue)
}
func _handler_method3(w http.ResponseWriter, r *http.Request) {
	body, bodyReadErr := io.ReadAll(r.Body)
	if bodyReadErr != nil {
		_handleBadRequest(w, bodyReadErr)
		return
	}
	type bodyType struct {
		BodyString  string  `json:"bodyString"`
		BodyInt     int     `json:"bodyInt"`
		BodyFloat64 float64 `json:"bodyFloat64"`
		BodyBool    bool    `json:"bodyBool"`
		BodyBytes   []byte  `json:"bodyBytes"`
	}
	bodyValue, bodyValueUnmarshalErr := _unmarshalBytes[bodyType](body)
	if bodyValueUnmarshalErr != nil {
		_handleBadRequest(w, bodyValueUnmarshalErr)
		return
	}
	result, _ := method3(bodyValue.BodyString, bodyValue.BodyInt, bodyValue.BodyFloat64, bodyValue.BodyBool, bodyValue.BodyBytes)
	type resultType struct {
		_baseResponse `json:",inline"`
		Result        string `json:"result"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Result: result}
	_handleResult(w, nil, resultValue)
}
func _handler_method4(w http.ResponseWriter, r *http.Request) {
	pathStringPath := r.PathValue("pathString")
	pathString, pathStringUnmarshalErr := _unmarshalString[string](pathStringPath)
	if pathStringUnmarshalErr != nil {
		_handleBadRequest(w, pathStringUnmarshalErr)
		return
	}
	queryStringQuery := r.URL.Query().Get("queryString")
	queryString, queryStringUnmarshalErr := _unmarshalString[string](queryStringQuery)
	if queryStringUnmarshalErr != nil {
		_handleBadRequest(w, queryStringUnmarshalErr)
		return
	}
	body, bodyReadErr := io.ReadAll(r.Body)
	if bodyReadErr != nil {
		_handleBadRequest(w, bodyReadErr)
		return
	}
	bodyString, bodyStringUnmarshalErr := _unmarshalBytes[string](body)
	if bodyStringUnmarshalErr != nil {
		_handleBadRequest(w, bodyStringUnmarshalErr)
		return
	}
	res0, res1 := method4(pathString, queryString, bodyString)
	type resultType struct {
		_baseResponse `json:",inline"`
		Res0          string `json:"res0"`
		Res1          error  `json:"res1"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Res0: res0, Res1: res1}
	_handleResult(w, res1, resultValue)
}
func _handler_method5(w http.ResponseWriter, r *http.Request) {
	body, bodyReadErr := io.ReadAll(r.Body)
	if bodyReadErr != nil {
		_handleBadRequest(w, bodyReadErr)
		return
	}
	bodyMap, bodyMapUnmarshalErr := _unmarshalBytes[map[string][]map[string]int](body)
	if bodyMapUnmarshalErr != nil {
		_handleBadRequest(w, bodyMapUnmarshalErr)
		return
	}
	result, Error := method5(bodyMap)
	type resultType struct {
		_baseResponse `json:",inline"`
		Result        string `json:"result"`
		Error         error  `json:"Error"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Result: result, Error: Error}
	_handleResult(w, Error, resultValue)
}
func _handler_method6(w http.ResponseWriter, r *http.Request) {
	field1Query := r.URL.Query().Get("field1")
	field1, field1UnmarshalErr := _unmarshalString[string](field1Query)
	if field1UnmarshalErr != nil {
		_handleBadRequest(w, field1UnmarshalErr)
		return
	}
	field2Query := r.URL.Query().Get("field2")
	field2, field2UnmarshalErr := _unmarshalString[int](field2Query)
	if field2UnmarshalErr != nil {
		_handleBadRequest(w, field2UnmarshalErr)
		return
	}
	field3Query := r.URL.Query().Get("field3")
	field3, field3UnmarshalErr := _unmarshalString[float64](field3Query)
	if field3UnmarshalErr != nil {
		_handleBadRequest(w, field3UnmarshalErr)
		return
	}
	field4Query := r.URL.Query().Get("field4")
	field4, field4UnmarshalErr := _unmarshalString[bool](field4Query)
	if field4UnmarshalErr != nil {
		_handleBadRequest(w, field4UnmarshalErr)
		return
	}
	field5Query := r.URL.Query().Get("field5")
	field5, field5UnmarshalErr := _unmarshalString[[]byte](field5Query)
	if field5UnmarshalErr != nil {
		_handleBadRequest(w, field5UnmarshalErr)
		return
	}
	code, err := method6(field1, field2, field3, field4, field5)
	type resultType struct {
		_baseResponse `json:",inline"`
		Code          int   `json:"code"`
		Err           error `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Code: code, Err: err}
	_handleResult(w, err, resultValue)
}
func _handler_method7(w http.ResponseWriter, r *http.Request) {
	body, bodyReadErr := io.ReadAll(r.Body)
	if bodyReadErr != nil {
		_handleBadRequest(w, bodyReadErr)
		return
	}
	type bodyType struct {
		BodyModel     ThisPackageModel                      `json:"bodyModel"`
		BodyModelList []ThisPackageModel                    `json:"bodyModelList"`
		BodyModelMap  map[string]models.AnotherPackageModel `json:"bodyModelMap"`
	}
	bodyValue, bodyValueUnmarshalErr := _unmarshalBytes[bodyType](body)
	if bodyValueUnmarshalErr != nil {
		_handleBadRequest(w, bodyValueUnmarshalErr)
		return
	}
	code, err := method7(bodyValue.BodyModel, bodyValue.BodyModelList, bodyValue.BodyModelMap)
	type resultType struct {
		_baseResponse `json:",inline"`
		Code          int   `json:"code"`
		Err           error `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Code: code, Err: err}
	_handleResult(w, err, resultValue)
}
func _handler_method8(w http.ResponseWriter, r *http.Request) {
	result, err := method8()
	type resultType struct {
		_baseResponse `json:",inline"`
		Result        string `json:"result"`
		Err           error  `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Result: result, Err: err}
	_handleResult(w, err, resultValue)
}
func _handler_method9(w http.ResponseWriter, r *http.Request) {
	result, err := method9()
	type resultType struct {
		_baseResponse `json:",inline"`
		Result        string `json:"result"`
		Err           error  `json:"err"`
	}
	resultValue := resultType{_baseResponse: _baseResponse{Code: http.StatusOK, Msg: http.StatusText(http.StatusOK)}, Result: result, Err: err}
	_handleResult(w, err, resultValue)
}
func init() {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /path-to-method1", _handler_method1)
	mux.HandleFunc("POST /path-to-method2", _handler_method2)
	mux.HandleFunc("PUT /path-to-method3", _handler_method3)
	mux.HandleFunc("DELETE /path-to-method4", _handler_method4)
	mux.HandleFunc("OPTIONS /path-to-method5", _handler_method5)
	mux.HandleFunc("HEAD /path-to-method6", _handler_method6)
	mux.HandleFunc("PATCH /path-to-method7", _handler_method7)
	mux.HandleFunc("GET /path-to-method8", _handler_method8)
	mux.HandleFunc("GET /path-to-method9", _handler_method9)
	s2aHandler = mux
}
