// Code generated by swag2api v1.0.0. DO NOT EDIT.
package testdata

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

var handler http.Handler

type _errorResponse struct {
	Error string `json:"error"`
}

func _unmarshalString[T any](value string) (buf T, err error) {
	return _unmarshalBytes[T]([]byte(value))
}
func _unmarshalBytes[T any](value []byte) (buf T, err error) {
	if err = json.Unmarshal(value, &buf); err != nil {
		return buf, fmt.Errorf("unmarshal: %w", err)
	}
	return buf, nil
}
func _handleBadRequest(w http.ResponseWriter, err error) {
	var (
		code = http.StatusBadRequest
		msg  = http.StatusText(http.StatusBadRequest)
	)
	if err != nil {
		msg = err.Error()
	}
	response := _errorResponse{Error: msg}
	_writeResponse(w, code, response)
}
func _handleResult(w http.ResponseWriter, err error, response any) {
	if err == nil {
		_writeResponse(w, http.StatusOK, response)
		return
	}
	if cu, ok := err.(interface {
		Code() int
		Unwrap() error
	}); ok {
		if e := cu.Unwrap(); e != nil {
			_writeResponse(w, cu.Code(), _errorResponse{Error: e.Error()})
		} else if response == nil {
			_writeResponse(w, cu.Code(), _errorResponse{Error: http.StatusText(cu.Code())})
		} else {
			_writeResponse(w, cu.Code(), response)
		}
		return
	}
	_writeResponse(w, http.StatusInternalServerError, _errorResponse{Error: err.Error()})
}
func _writeResponse(w http.ResponseWriter, code int, response any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(response)
}
func _handler_function1(w http.ResponseWriter, r *http.Request) {
	paramStringPath := r.PathValue("paramString")
	paramString, paramStringUnmarshalErr := _unmarshalString[string](paramStringPath)
	if paramStringUnmarshalErr != nil {
		_handleBadRequest(w, paramStringUnmarshalErr)
		return
	}
	paramIntQuery := r.URL.Query().Get("paramInt")
	paramInt, paramIntUnmarshalErr := _unmarshalString[int](paramIntQuery)
	if paramIntUnmarshalErr != nil {
		_handleBadRequest(w, paramIntUnmarshalErr)
		return
	}
	resultString, resultError := function1(paramString, paramInt)
	type _resultType struct {
		ResultString string `json:"resultString"`
	}
	_resultValue := _resultType{ResultString: resultString}
	_handleResult(w, resultError, _resultValue)
}
func _handler_function2(w http.ResponseWriter, r *http.Request) {
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	paramString, paramStringUnmarshalErr := _unmarshalBytes[string](_body)
	if paramStringUnmarshalErr != nil {
		_handleBadRequest(w, paramStringUnmarshalErr)
		return
	}
	resultString, _ := function2(paramString)
	type _resultType struct {
		ResultString string `json:"resultString"`
	}
	_resultValue := _resultType{ResultString: resultString}
	_handleResult(w, nil, _resultValue)
}
func _handler_function3(w http.ResponseWriter, r *http.Request) {
	_body, _bodyReadErr := io.ReadAll(r.Body)
	if _bodyReadErr != nil {
		_handleBadRequest(w, _bodyReadErr)
		return
	}
	type _bodyType struct {
		ParamString string `json:"paramString"`
		ParamInt    int    `json:"paramInt"`
	}
	_bodyValue, _bodyValueUnmarshalErr := _unmarshalBytes[_bodyType](_body)
	if _bodyValueUnmarshalErr != nil {
		_handleBadRequest(w, _bodyValueUnmarshalErr)
		return
	}
	resultError := function3(_bodyValue.ParamString, _bodyValue.ParamInt)
	type _resultType struct {
		ResultError bool `json:"resultError"`
	}
	_resultValue := _resultType{ResultError: resultError}
	_handleResult(w, nil, _resultValue)
}
func init() {
	_mux := http.NewServeMux()
	_mux.HandleFunc("GET path-to-function1", _handler_function1)
	_mux.HandleFunc("POST path-to-function2", _handler_function2)
	_mux.HandleFunc("PATCH path-to-function3", _handler_function3)
	handler = _mux
}
