package builder

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"log"
	"os"
	"strconv"

	"golang.org/x/tools/imports"

	filecompiler "github.com/KianIt/swag2api/builder/ast/file-compiler"
	astm "github.com/KianIt/swag2api/builder/ast/models"
	asttemplate "github.com/KianIt/swag2api/builder/ast/template"
	templateModels "github.com/KianIt/swag2api/builder/ast/template/models"
	"github.com/KianIt/swag2api/builder/models"
	"github.com/KianIt/swag2api/constants"
	s2aModels "github.com/KianIt/swag2api/models"
	parserModels "github.com/KianIt/swag2api/parser/models"
)

var genComment = fmt.Sprintf("// Code generated by swag2api v%s. DO NOT EDIT.\n", constants.Version)

// Builder is a code generator for the API.
//
// It builds an abstract syntax tree (AST) by given
// parsing information and dumps it to a file.
type Builder struct {
	p  parserModels.ParsingInfo
	tm *asttemplate.Manager
	fc *filecompiler.FileCompiler
}

// NewBuilder returns a new builder.
func NewBuilder(parsingInfo parserModels.ParsingInfo) *Builder {
	return &Builder{
		p:  parsingInfo,
		tm: asttemplate.NewManager(),
		fc: filecompiler.NewFileCompiler(parsingInfo.PkgName),
	}
}

// Build runs API generating.
//
// Loads templates, builds the AST and saves the source code to a file.
func (b *Builder) Build(apiPath string) error {
	log.Printf("Building into '%s'", apiPath)

	if err := b.tm.Load(); err != nil {
		return fmt.Errorf("loading templates: %w", err)
	}

	b.buildAST()

	if err := b.saveToFile(apiPath); err != nil {
		return fmt.Errorf("saving to file: %w", err)
	}

	log.Printf("Built successfully")

	return nil
}

// saveToFile dumps the AST and saves the source code to a file.
func (b *Builder) saveToFile(apiPath string) error {
	file, err := os.Create(apiPath)
	if err != nil {
		return fmt.Errorf("creating file: %w", err)
	}

	astDump, err := b.dumpAST()
	if err != nil {
		return fmt.Errorf("dumping AST: %w", err)
	}

	if _, err = file.Write(append([]byte(genComment), astDump...)); err != nil {
		return fmt.Errorf("writing to file: %w", err)
	}

	return nil
}

// dumpAST dumps the AST and processes the source code imports.
func (b *Builder) dumpAST() ([]byte, error) {
	var buf bytes.Buffer

	astFile := b.fc.Compile()

	if err := format.Node(&buf, token.NewFileSet(), astFile); err != nil {
		return nil, fmt.Errorf("formatting node: %w", err)
	}

	astDump, err := imports.Process("", buf.Bytes(), nil)
	if err != nil {
		return nil, fmt.Errorf("sorting imports: %w", err)
	}

	return astDump, nil
}

// buildAST build the AST.
func (b *Builder) buildAST() {
	b.addImports()
	b.addHTTPHandler()
	b.addTemplates()
	b.addFuncHandlers()
	b.addInit()
}

// addImports adds imports to the AST.
//
// Adds necessary imports and imports from parsed files.
func (b *Builder) addImports() {
	b.addImport("encoding/json")
	b.addImport("net/http")
	b.addImport("strconv")
	b.addImport("io")

	for _, imp := range b.p.Imports {
		b.addAliasedImport(imp.Path, imp.Alias)
	}
}

// addImport adds import without an alias to the AST.
func (b *Builder) addImport(path string) {
	b.addAliasedImport(path, "")
}

// addAliasedImport adds import with an alias to the AST.
func (b *Builder) addAliasedImport(path, alias string) {
	b.fc.AddImport(path, alias)
}

// addHTTPHandler adds an HTTP handler for the API to the AST.
//
// Adds an HTTP handler declaration, if it doesn't exist.
func (b *Builder) addHTTPHandler() {
	if b.p.HTTPHandler.Exists {
		return
	}

	b.fc.AddDecl(astm.GetVarDecl(b.p.HTTPHandler.Name, models.HandlerToken.String()))
}

// addTemplates add source code templates to the AST.
//
// Gets templates from the template manager and adds the templates to the AST.
func (b *Builder) addTemplates() {
	decls, err := b.tm.GetTemplates()
	if err != nil {
		log.Printf("Error: couldn't get templates: %v", err)
		return
	}

	for _, decl := range decls {
		b.fc.AddDecl(decl)
	}
}

// addInit adds the init function to the AST.
//
// Adds the init function that is called on the package loading
// and setups function handlers dispatching by the HTTP handler.
func (b *Builder) addInit() {
	var bodyStmts astm.Stmts

	bodyStmts = append(bodyStmts,
		astm.GetAssignDefineStmt(
			astm.Exprs{models.MuxToken.AstExpr()},
			astm.Exprs{astm.GetCallExpr(models.NewMuxToken.AstExpr(), nil)},
		),
	)

	for _, f := range b.p.Funcs {
		bodyStmts = append(bodyStmts,
			astm.GetExprStmt(
				astm.GetCallExpr(
					astm.GetSelectorExpr(models.MuxToken.AstExpr(), models.HandleFuncToken.String()),
					astm.Exprs{
						astm.GetNameExpr(strconv.Quote(f.Endpoint.HandlerPath())),
						astm.GetNameExpr(f.HandlerName()),
					},
				),
			),
		)
	}

	bodyStmts = append(bodyStmts,
		astm.GetAssignStmt(
			astm.Exprs{astm.GetNameExpr(b.p.HTTPHandler.Name)},
			astm.Exprs{models.MuxToken.AstExpr()},
		),
	)

	b.fc.AddDecl(
		astm.GetFuncDecl(
			models.InitToken.String(),
			nil,
			bodyStmts,
		),
	)
}

// addFuncHandlers adds function handlers to the AST.
func (b *Builder) addFuncHandlers() {
	for _, f := range b.p.Funcs {
		b.addFuncHandler(f)
	}
}

// addFuncHandler adds a function handler to the AST.
//
// Adds a function handler that processes a certain request.
// Gets params from the request, passes them to the function,
// gets results and writes a response.
func (b *Builder) addFuncHandler(f s2aModels.Function) {
	var bodyStmts astm.Stmts

	paramStmts, isBodyStruct := b.getFuncHandlerParamStmts(f)
	bodyStmts = append(bodyStmts,
		paramStmts...,
	)

	bodyStmts = append(bodyStmts,
		getFuncHandlerFuncCallStmts(f, isBodyStruct)...,
	)

	bodyStmts = append(bodyStmts,
		getFuncHandlerResultStmts(f)...,
	)

	b.fc.AddDecl(
		astm.GetFuncDecl(
			f.HandlerName(),
			[]astm.Field{
				astm.GetField(models.WToken.String(), models.WriterToken.String(), ""),
				astm.GetField(models.RToken.String(), models.RequestToken.String(), ""),
			},
			bodyStmts,
		),
	)
}

// getFuncHandlerParamStmts returns AST statements for function params processing.
func (b *Builder) getFuncHandlerParamStmts(f s2aModels.Function) (paramStmts astm.Stmts, isBodyStruct bool) {
	var bodyParams []s2aModels.Param

	for _, param := range f.Params {
		switch param.Origin {
		case s2aModels.Path, s2aModels.Query:
			var (
				paramNameExpr = astm.GetNameExpr(strconv.Quote(param.Name))
				paramGet      astm.Expr
			)

			if param.Origin == s2aModels.Path {
				paramGet = astm.GetCallExpr(
					models.PathValueGetToken.AstExpr(),
					astm.Exprs{paramNameExpr},
				)
			} else {
				paramGet = astm.GetCallExpr(
					models.QueryValueGetToken.AstExpr(),
					astm.Exprs{paramNameExpr},
				)
			}

			paramStmts = append(paramStmts,
				astm.GetAssignDefineStmt(
					astm.Exprs{astm.GetNameExpr(param.NameOrigin())},
					astm.Exprs{paramGet},
				),
			)

			unmarshalStmt, unmarshalErrName := getFuncHandlerParamUnmarshalStmt(param.NameOrigin(), param.Name, param.TypeExpr, false)
			paramStmts = append(paramStmts,
				unmarshalStmt,
			)

			paramStmts = append(paramStmts,
				getHandleBadRequestStmt(unmarshalErrName),
			)
		case s2aModels.Body:
			bodyParams = append(bodyParams, param)
		}
	}

	if len(bodyParams) == 0 {
		return paramStmts, false
	}

	bodyParamStmts, isBodyStruct := getFuncHandlerBodyParamStmts(bodyParams)
	paramStmts = append(paramStmts,
		bodyParamStmts...,
	)

	return paramStmts, isBodyStruct
}

// getFuncHandlerBodyParamStmts returns AST statements for body params processing.
func getFuncHandlerBodyParamStmts(params []s2aModels.Param) (paramStmts astm.Stmts, isStruct bool) {
	paramStmts = append(paramStmts,
		astm.GetAssignDefineStmt(
			astm.Exprs{models.BodyToken.AstExpr(), models.BodyReadErrToken.AstExpr()},
			astm.Exprs{models.BodyGetToken.AstExpr()}),
		getHandleBadRequestStmt(models.BodyReadErrToken.String()),
	)

	var paramName, paramTypeExpr string
	if len(params) > 1 {
		var fields = make([]astm.Field, 0, len(params))

		for _, param := range params {
			fields = append(fields,
				astm.GetField(
					param.NameCapitalized(),
					param.TypeExpr,
					param.JSONTag(),
				),
			)
		}

		paramStmts = append(paramStmts,
			astm.GetStructStmt(
				models.BodyTypeToken.String(),
				fields,
			),
		)

		paramName = models.BodyValueToken.String()
		paramTypeExpr = models.BodyTypeToken.String()

		isStruct = true
	} else {
		paramName = params[0].Name
		paramTypeExpr = params[0].TypeExpr

		isStruct = false
	}

	unmarshalStmt, unmarshalErrName := getFuncHandlerParamUnmarshalStmt(models.BodyToken.String(), paramName, paramTypeExpr, true)
	paramStmts = append(paramStmts,
		unmarshalStmt,
	)

	paramStmts = append(paramStmts,
		getHandleBadRequestStmt(unmarshalErrName),
	)

	return paramStmts, isStruct
}

// getFuncHandlerParamUnmarshalStmt returns an AST statement for param unmarshalling.
func getFuncHandlerParamUnmarshalStmt(paramNameOrigin, paramName, typeExpr string, isBody bool) (astm.Stmt, string) {
	var caller string
	if !isBody {
		caller = templateModels.UnmarshalString
	} else {
		caller = templateModels.UnmarshalBytes
	}
	callerExpr := astm.GetNameExpr(fmt.Sprintf("%s[%s]", caller, typeExpr))

	errName := paramName + models.UnmarshalErrSuffixToken.String()

	return astm.GetAssignDefineStmt(
		astm.Exprs{
			astm.GetNameExpr(paramName),
			astm.GetNameExpr(errName),
		},
		astm.Exprs{
			astm.GetCallExpr(
				callerExpr,
				astm.Exprs{astm.GetNameExpr(paramNameOrigin)},
			),
		},
	), errName
}

// getFuncHandlerFuncCallStmts returns AST statements for function calling.
func getFuncHandlerFuncCallStmts(f s2aModels.Function, isBodyStruct bool) (stmts astm.Stmts) {
	resultExprs := make(astm.Exprs, 0, len(f.Results))
	for _, result := range f.Results {
		resultExprs = append(resultExprs, astm.GetNameExpr(result.Name))
	}

	paramExprs := make(astm.Exprs, 0, len(f.Params))
	for _, param := range f.Params {
		var paramExpr astm.Expr
		if param.Origin == s2aModels.Body && isBodyStruct {
			paramExpr = astm.GetSelectorExpr(models.BodyValueToken.AstExpr(), param.NameCapitalized())
		} else {
			paramExpr = astm.GetNameExpr(param.Name)
		}
		paramExprs = append(paramExprs, paramExpr)
	}

	stmts = append(stmts,
		astm.GetAssignDefineStmt(
			resultExprs,
			astm.Exprs{
				astm.GetCallExpr(astm.GetNameExpr(f.Name), paramExprs),
			},
		),
	)

	return stmts
}

// getFuncHandlerResultStmts returns AST statements for function results processing.
func getFuncHandlerResultStmts(f s2aModels.Function) (stmts astm.Stmts) {
	fields := make([]astm.Field, 0, len(f.Results)+1)
	elements := make(astm.Exprs, 0, len(f.Results)+1)

	resultErrExists := false
	resultErrName := ""
	for _, result := range f.Results {
		if result.Name == "_" {
			continue
		}

		if result.IsError() {
			resultErrExists = true
			resultErrName = result.Name
			continue
		}

		fields = append(
			fields,
			astm.GetField(
				result.NameCapitalized(),
				result.TypeExpr,
				result.JSONTag(),
			),
		)

		elements = append(
			elements,
			astm.GetKeyValueExpr(
				astm.GetNameExpr(result.NameCapitalized()),
				astm.GetNameExpr(result.Name),
			),
		)
	}

	stmts = append(
		stmts,
		astm.GetStructStmt(
			models.ResultTypeToken.String(),
			fields,
		),
		astm.GetAssignDefineStmt(
			astm.Exprs{models.ResultValueToken.AstExpr()},
			astm.Exprs{
				astm.GetStructLitExpr(
					models.ResultTypeToken.String(),
					elements,
				),
			},
		),
	)

	if resultErrExists {
		stmts = append(
			stmts,
			getHandleResultStmt(resultErrName),
		)
	} else {
		stmts = append(
			stmts,
			getHandleResultStmt(models.NilToken.String()),
		)
	}

	return stmts
}

// getHandleResultStmt returns an AST statement for handing bad request.
func getHandleBadRequestStmt(errName string) astm.Stmt {
	var errExpr = astm.GetNameExpr(errName)

	return astm.GetIfStmt(
		astm.GetNeqExpr(errExpr, models.NilToken.AstExpr()),
		astm.Stmts{
			astm.GetExprStmt(
				astm.GetCallExpr(
					astm.GetNameExpr(templateModels.HandleBadRequest),
					astm.Exprs{models.WToken.AstExpr(), errExpr},
				),
			),
			astm.GetExprStmt(models.ReturnToken.AstExpr()),
		},
	)
}

// getHandleResultStmt returns an AST statement for handing function results.
func getHandleResultStmt(errName string) astm.Stmt {
	return astm.GetExprStmt(
		astm.GetCallExpr(
			astm.GetNameExpr(templateModels.HandleResult),
			astm.Exprs{
				models.WToken.AstExpr(),
				astm.GetNameExpr(errName),
				models.ResultValueToken.AstExpr(),
			},
		),
	)
}
